In [2]:
import pandas as pd
import numpy as np
import sys 
sys.path.append('../') 
from lib.constants import Constants

In [3]:
from lib.datacleaning import data_cleaning_pipline
from lib.dataio import prepare_data_pipline, DataBox
from model.lgbmodel import lgb_model

In [4]:
all_df = prepare_data_pipline()

/media/xuchen/E0BC709EBC707140/DeskTopDOC/Jupyter/project201901/testbox

In [5]:
all_df

,Sample_id,A1,A2,A3,A4,A5,A6,A7,A8,A9,...,B6,B7,B8,B9,B10,B11,B12,B13,B14,Yield
0,sample_1528,300,NaN,405.0,700,13:30:00,38.0,NaN,NaN,15:30:00,...,65,11:30:00,45.0,11:30-13:00,14:00-15:30,NaN,800.0,0.15,400,0.879
1,sample_1698,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,6:00:00,45.0,6:00-7:30,7:30-9:00,9:00-10:00,1200.0,0.15,400,0.902
2,sample_639,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:00,1200.0,0.15,400,0.936
3,sample_483,300,NaN,405.0,700,1:30:00,38.0,NaN,NaN,3:00:00,...,65,18:00:00,45.0,19:00-20:30,21:30-23:00,NaN,800.0,0.15,400,0.902
4,sample_617,300,NaN,405.0,700,22:00:00,29.0,NaN,NaN,0:00:00,...,80,9:00:00,45.0,9:00-10:30,10:30-12:00,12:00-13:00,1200.0,0.15,420,0.983
5,sample_373,300,NaN,405.0,700,2:00:00,39.0,2:30:00,80.0,3:30:00,...,65,3:00:00,45.0,3:00-4:30,5:30-7:00,NaN,800.0,0.15,420,0.935
6,sample_577,300,NaN,405.0,700,8:00:00,29.0,NaN,NaN,10:00:00,...,80,19:00:00,45.0,19:00-20:30,20:30-22:00,22:00-23:00,1200.0,0.15,400,0.902
7,sample_212,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,400,0.891
8,sample_521,300,NaN,405.0,700,17:30:00,21.0,NaN,NaN,19:00:00,...,65,6:30:00,45.0,6:30-8:00,8:30-10:00,NaN,800.0,0.15,420,0.947
9,sample_1026,300,NaN,405.0,700,11:00:00,21.0,NaN,NaN,12:30:00,...,64,2:00:00,50.0,6:00-7:30,8:00-9:30,NaN,800.0,0.15,400,0.902
10,sample_1743,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,78,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:30,1200.0,0.15,400,0.936
11,sample_1493,300,NaN,405.0,700,21:00:00,37.0,21:20:00,80.0,23:00:00,...,65,21:00:00,30.0,21:00-22:30,23:00-0:30,NaN,800.0,0.15,400,0.891
12,sample_1613,300,NaN,405.0,700,11:00:00,33.0,NaN,NaN,12:30:00,...,65,4:00:00,50.0,4:00-5:30,6:00-7:30,NaN,800.0,0.15,400,0.891
13,sample_621,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,74,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,400,0.947
14,sample_1269,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,400,0.925
15,sample_1037,300,NaN,405.0,700,21:00:00,21.0,NaN,NaN,22:30:00,...,65,13:00:00,45.0,14:00-15:30,16:30-18:00,NaN,800.0,0.15,400,0.902
16,sample_1736,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,420,0.971
17,sample_97,300,NaN,405.0,700,16:00:00,29.0,NaN,NaN,18:00:00,...,80,21:00:00,45.0,3:00-4:30,4:30-6:00,6:00-7:00,1200.0,0.15,400,0.902
18,sample_642,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:00,1200.0,0.15,400,0.913
19,sample_179,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,78,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:00,1200.0,0.15,400,0.925
20,sample_759,300,NaN,405.0,700,4:30:00,27.0,NaN,NaN,6:30:00,...,80,15:30:00,45.0,15:30-19:00,NaN,NaN,1200.0,0.15,440,0.930
21,sample_812,300,NaN,405.0,700,6:00:00,30.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-21:00,NaN,NaN,1200.0,0.15,440,0.930
22,sample_1395,300,NaN,405.0,700,14:00:00,30.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-5:00,NaN,NaN,1200.0,0.15,440,0.930
23,sample_922,300,NaN,405.0,700,19:30:00,38.0,19:40:00,80.0,21:00:00,...,45,21:00:00,40.0,21:30-23:0,23:30-1:00,NaN,800.0,0.15,420,0.947
24,sample_514,300,NaN,405.0,700,11:00:00,26.0,NaN,NaN,12:30:00,...,65,8:00:00,45.0,8:00-9:30,10:00-11:30,NaN,800.0,0.15,420,0.935
25,sample_72,300,NaN,405.0,700,22:00:00,30.0,NaN,NaN,0:00:00,...,78,9:00:00,45.0,9:00-10:30,10:30-12:00,12:00-13:00,1200.0,0.15,420,0.971
26,sample_1344,300,NaN,405.0,700,6:00:00,30.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-21:00,NaN,NaN,1200.0,0.15,440,0.930
27,sample_582,300,NaN,405.0,700,9:30:00,20.0,NaN,NaN,11:30:00,...,65,19:30:00,45.0,19:30-20:30,21:30-22:00,NaN,1200.0,0.15,420,0.935
28,sample_1002,300,NaN,405.0,700,14:00:00,21.0,NaN,NaN,15:00:00,...,60,4:00:00,39.0,4:30-6:00,7:00-8:00,NaN,800.0,0.15,380,0.878
29,sample_1079,300,NaN,405.0,700,1:00:00,27.0,NaN,NaN,2:30:00,...,65,22:00:00,45.0,0:00-1:30,2:30-4:00,NaN,800.0,0.15,400,0.902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1516,sample_49,300,NaN,405.0,700,22:00:00,20.0,NaN,NaN,23:00:00,...,67,7:30:00,45.0,7:30-9:00,9:30-11:00,NaN,800.0,0.15,400,-1.000
1517,sample_474,300,NaN,405.0,700,12:00:00,32.0,NaN,NaN,13:30:00,...,60,6:00:00,40.0,6:00-7:30,8:00-9:30,NaN,800.0,0.15,400,-1.000
1518,sample_1716,300,NaN,405.0,700,5:00:00,18.0,NaN,NaN,6:30:00,...,76,15:30:00,45.0,15:30-17:00,17:30-19:00,NaN,800.0,0.15,400,-1.000
1519,sample_1169,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,9:00:00,45.0,9:00-10:30,10:30-12:00,12:00-13:00,1200.0,0.15,420,-1.000
1520,sample_1925,300,NaN,405.0,700,6:00:00,30.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-21:00,NaN,NaN,1200.0,0.15,440,-1.000
1521,sample_667,300,NaN,405.0,700,22:00:00,30.0,NaN,NaN,0:00:00,...,80,9:00:00,45.0,9:00-10:30,10:30-12:00,12:00-13:00,1200.0,0.15,400,-1.000
1522,sample_176,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:00,1200.0,0.15,400,-1.000
1523,sample_1908,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,400,-1.000
1524,sample_160,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,77,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,400,-1.000
1525,sample_35,300,NaN,405.0,700,22:00:00,21.0,NaN,NaN,23:00:00,...,65,22:00:00,40.0,22:30-0:00,0:30-2:00,NaN,800.0,0.15,440,-1.000
1526,sample_1403,300,NaN,405.0,700,21:00:00,29.0,NaN,NaN,23:00:00,...,80,8:00:00,45.0,8:00-9:30,9:30-11:00,11:00-12:00,1200.0,0.15,440,-1.000
1527,sample_1806,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:00,1200.0,0.15,420,-1.000
1528,sample_241,300,NaN,405.0,700,6:00:00,30.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-21:00,NaN,NaN,1200.0,0.15,440,-1.000
1529,sample_1059,300,NaN,405.0,700,16:30:00,21.0,NaN,NaN,18:00:00,...,65,12:00:00,50.0,12:00-13:30,14:00-15:30,NaN,800.0,0.15,420,-1.000
1530,sample_746,300,NaN,405.0,700,22:00:00,29.0,NaN,NaN,0:00:00,...,80,9:00:00,45.0,9:00-12:00,NaN,NaN,1200.0,0.15,440,-1.000
1531,sample_513,300,NaN,405.0,700,22:30:00,21.0,NaN,NaN,0:00:00,...,65,22:00:00,45.0,22:00-23:30,0:30-2:00,NaN,800.0,0.15,420,-1.000
1532,sample_1088,300,NaN,405.0,700,15:30:00,26.0,NaN,NaN,16:00:00,...,65,13:00:00,45.0,14:30-16:00,16:30-18:00,NaN,800.0,0.15,420,-1.000
1533,sample_1370,300,NaN,405.0,700,6:00:00,28.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-21:00,NaN,NaN,1200.0,0.15,440,-1.000
1534,sample_523,300,NaN,405.0,700,5:00:00,23.0,NaN,NaN,6:30:00,...,65,22:00:00,45.0,0:30-2:00,3:00-4:30,NaN,800.0,0.15,420,-1.000
1535,sample_319,300,NaN,405.0,700,21:00:00,37.0,0:50:00,80.0,22:50:00,...,65,20:30:00,28.0,20:30-22:00,22:30-23:50,NaN,800.0,0.15,400,-1.000
1536,sample_1923,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-5:00,NaN,NaN,1200.0,0.15,460,-1.000
1537,sample_1296,300,NaN,405.0,700,21:00:00,30.0,NaN,NaN,23:00:00,...,80,8:00:00,45.0,8:00-11:00,NaN,NaN,1200.0,0.15,440,-1.000
1538,sample_1152,300,NaN,405.0,700,18:00:00,29.0,NaN,NaN,20:00:00,...,80,5:00:00,45.0,5:00-6:30,6:30-8:00,8:00-9:00,1200.0,0.15,400,-1.000
1539,sample_982,300,NaN,405.0,700,22:00:00,21.0,NaN,NaN,23:30:00,...,67,13:20:00,45.0,13:40-15:10,15:40-17:10,NaN,900.0,0.15,400,-1.000
1540,sample_304,300,125.0,NaN,980,17:00:00,21.0,NaN,NaN,18:30:00,...,60,21:00:00,40.0,21:00-22:30,23:00-0:30,NaN,800.0,0.15,400,-1.000
1541,sample_502,300,NaN,405.0,700,11:00:00,24.0,NaN,NaN,12:30:00,...,65,10:30:00,45.0,12:30-14:00,14:30-16:00,NaN,800.0,0.15,440,-1.000
1542,sample_1951,300,NaN,405.0,700,21:00:00,29.0,NaN,NaN,23:00:00,...,80,8:00:00,45.0,8:00-12:00,NaN,NaN,1200.0,0.15,440,-1.000
1543,sample_386,300,NaN,405.0,700,7:30:00,41.0,7:40:00,80.0,9:00:00,...,40,4:30:00,20.0,4:30-6:00,6:00-7:30,NaN,800.0,0.15,440,-1.000
1544,sample_362,300,NaN,405.0,700,2:00:00,36.0,2:10:00,80.0,3:30:00,...,65,17:00:00,45.0,17:00-18:30,19:00-20:30,NaN,800.0,0.15,420,-1.000
1545,sample_522,300,NaN,405.0,700,22:00:00,29.0,NaN,NaN,23:30:00,...,65,14:00:00,50.0,14:00-15:30,16:30-18:00,NaN,800.0,0.15,420,-1.000

#### 缺失值情况

In [5]:
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1546 entries, 0 to 1545
Data columns (total 44 columns):
Sample_id    1546 non-null object
A1           1546 non-null int64
A2           45 non-null float64
A3           1501 non-null float64
A4           1546 non-null int64
A5           1546 non-null object
A6           1546 non-null float64
A7           167 non-null object
A8           167 non-null float64
A9           1546 non-null object
A10          1546 non-null int64
A11          1546 non-null object
A12          1546 non-null float64
A13          1546 non-null float64
A14          1546 non-null object
A15          1546 non-null float64
A16          1546 non-null object
A17          1546 non-null float64
A18          1546 non-null float64
A19          1546 non-null int64
A20          1545 non-null object
A21          1543 non-null float64
A22          1546 non-null float64
A23          1543 non-null float64
A24          1545 non-null object
A25          1545 non-null object
A26          1544 non-null object
A27          1545 non-null float64
A28          1546 non-null object
B1           1535 non-null float64
B2           1544 non-null float64
B3           1544 non-null float64
B4           1546 non-null object
B5           1545 non-null object
B6           1546 non-null int64
B7           1546 non-null object
B8           1545 non-null float64
B9           1546 non-null object
B10          1280 non-null object
B11          608 non-null object
B12          1545 non-null float64
B13          1545 non-null float64
B14          1546 non-null int64
Yield        1546 non-null float64
dtypes: float64(20), int64(6), object(18)
memory usage: 531.5+ KB

In [7]:
for col in all_df[all_df['Yield']==-1].columns:
    print(col + ': ' + str(all_df[col].unique().shape[0]))
    print('============================')

Sample_id: 1546
============================
A1: 3
============================
A2: 2
============================
A3: 4
============================
A4: 4
============================
A5: 68
============================
A6: 39
============================
A7: 80
============================
A8: 9
============================
A9: 98
============================
A10: 4
============================
A11: 97
============================
A12: 10
============================
A13: 3
============================
A14: 95
============================
A15: 11
============================
A16: 97
============================
A17: 14
============================
A18: 2
============================
A19: 8
============================
A20: 168
============================
A21: 13
============================
A22: 4
============================
A23: 4
============================
A24: 94
============================
A25: 23
============================
A26: 91
============================
A27: 14
============================
A28: 165
============================
B1: 22
============================
B2: 4
============================
B3: 3
============================
B4: 183
============================
B5: 63
============================
B6: 36
============================
B7: 59
============================
B8: 26
============================
B9: 193
============================
B10: 192
============================
B11: 40
============================
B12: 5
============================
B13: 4
============================
B14: 22
============================
Yield: 74
============================

### 4种原料之间的关系(A1 - A4), 倾向于这几个字段表示原料的浓度

In [12]:
MATERIAL_GROUP_1 = ['A1', 'A2', 'A3', 'A4']

A1没有缺失值,为必须原料

In [10]:
all_df['A2'].unique()

array([ nan, 125.])

In [29]:
all_df['A3'].unique()

array([405., 340.,   0., 270.])

In [40]:
all_df.loc[all_df['A3']==0, 'A4'].unique()

array([980])

In [42]:
all_df.loc[(all_df['A1']==300)&(all_df['A2']==125)&(all_df['A4']==980), 'A3'].unique()

array([0.])

认为这几个字段中,A2缺失值为不添加该原料, __对于所有A3中的缺失值,有所有:A1=300, A2=125, A4=980, 反过来看,A1/2/4等于这几个值时,A3唯一为空==>因此A3也被认为空值即为不添加原料__

In [15]:
for col in MATERIAL_GROUP_1:
    all_df[col].fillna(0, inplace=True)

In [17]:
sum_ = all_df['A1'] + all_df['A2'] + all_df['A3'] + all_df['A4']

In [20]:
sum_.unique().shape

(4,)

In [25]:
sum_ = all_df['A2'] + all_df['A3'] + all_df['A4']

In [26]:
sum_.unique().shape

(3,)

In [28]:
((all_df['A2'] + all_df['A4']) == (all_df['A3'] + all_df['A4'])).unique()

array([False], dtype=object)

In [43]:
all_df['A_1_2_3_4'] = all_df['A1'] + all_df['A2'] + all_df['A3'] + all_df['A4']

In [44]:
all_df['A_2_3_4'] = all_df['A2'] + all_df['A3'] + all_df['A4']

In [54]:
import itertools
from sklearn.preprocessing import LabelEncoder

In [57]:
for col in itertools.combinations(MATERIAL_GROUP_1, 2):
    combin_col = all_df[col[0]].astype(str) + all_df[col[1]].astype(str)
    encoder = LabelEncoder()
    combin_col = encoder.fit_transform(combin_col)
    all_df[col[0] + '_' + col[1]] = combin_col

In [58]:
all_df

,Sample_id,A1,A2,A3,A4,A5,A6,A7,A8,A9,...,B14,Yield,A_1_2_3_4,A_2_3_4,A1_A2,A1_A3,A1_A4,A2_A3,A2_A4,A3_A4
0,sample_1528,300,0.0,405.0,700,13:30:00,38.0,NaN,NaN,15:30:00,...,400,0.879,1405.0,1105.0,2,4,3,2,2,3
1,sample_1698,300,0.0,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,400,0.902,1405.0,1105.0,2,4,3,2,2,3
2,sample_639,300,0.0,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,400,0.936,1405.0,1105.0,2,4,3,2,2,3
3,sample_483,300,0.0,405.0,700,1:30:00,38.0,NaN,NaN,3:00:00,...,400,0.902,1405.0,1105.0,2,4,3,2,2,3
4,sample_617,300,0.0,405.0,700,22:00:00,29.0,NaN,NaN,0:00:00,...,420,0.983,1405.0,1105.0,2,4,3,2,2,3
5,sample_373,300,0.0,405.0,700,2:00:00,39.0,2:30:00,80.0,3:30:00,...,420,0.935,1405.0,1105.0,2,4,3,2,2,3
6,sample_577,300,0.0,405.0,700,8:00:00,29.0,NaN,NaN,10:00:00,...,400,0.902,1405.0,1105.0,2,4,3,2,2,3
7,sample_212,300,0.0,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,400,0.891,1405.0,1105.0,2,4,3,2,2,3
8,sample_521,300,0.0,405.0,700,17:30:00,21.0,NaN,NaN,19:00:00,...,420,0.947,1405.0,1105.0,2,4,3,2,2,3
9,sample_1026,300,0.0,405.0,700,11:00:00,21.0,NaN,NaN,12:30:00,...,400,0.902,1405.0,1105.0,2,4,3,2,2,3
10,sample_1743,300,0.0,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,400,0.936,1405.0,1105.0,2,4,3,2,2,3
11,sample_1493,300,0.0,405.0,700,21:00:00,37.0,21:20:00,80.0,23:00:00,...,400,0.891,1405.0,1105.0,2,4,3,2,2,3
12,sample_1613,300,0.0,405.0,700,11:00:00,33.0,NaN,NaN,12:30:00,...,400,0.891,1405.0,1105.0,2,4,3,2,2,3
13,sample_621,300,0.0,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,400,0.947,1405.0,1105.0,2,4,3,2,2,3
14,sample_1269,300,0.0,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,400,0.925,1405.0,1105.0,2,4,3,2,2,3
15,sample_1037,300,0.0,405.0,700,21:00:00,21.0,NaN,NaN,22:30:00,...,400,0.902,1405.0,1105.0,2,4,3,2,2,3
16,sample_1736,300,0.0,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,420,0.971,1405.0,1105.0,2,4,3,2,2,3
17,sample_97,300,0.0,405.0,700,16:00:00,29.0,NaN,NaN,18:00:00,...,400,0.902,1405.0,1105.0,2,4,3,2,2,3
18,sample_642,300,0.0,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,400,0.913,1405.0,1105.0,2,4,3,2,2,3
19,sample_179,300,0.0,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,400,0.925,1405.0,1105.0,2,4,3,2,2,3
20,sample_759,300,0.0,405.0,700,4:30:00,27.0,NaN,NaN,6:30:00,...,440,0.930,1405.0,1105.0,2,4,3,2,2,3
21,sample_812,300,0.0,405.0,700,6:00:00,30.0,NaN,NaN,8:00:00,...,440,0.930,1405.0,1105.0,2,4,3,2,2,3
22,sample_1395,300,0.0,405.0,700,14:00:00,30.0,NaN,NaN,16:00:00,...,440,0.930,1405.0,1105.0,2,4,3,2,2,3
23,sample_922,300,0.0,405.0,700,19:30:00,38.0,19:40:00,80.0,21:00:00,...,420,0.947,1405.0,1105.0,2,4,3,2,2,3
24,sample_514,300,0.0,405.0,700,11:00:00,26.0,NaN,NaN,12:30:00,...,420,0.935,1405.0,1105.0,2,4,3,2,2,3
25,sample_72,300,0.0,405.0,700,22:00:00,30.0,NaN,NaN,0:00:00,...,420,0.971,1405.0,1105.0,2,4,3,2,2,3
26,sample_1344,300,0.0,405.0,700,6:00:00,30.0,NaN,NaN,8:00:00,...,440,0.930,1405.0,1105.0,2,4,3,2,2,3
27,sample_582,300,0.0,405.0,700,9:30:00,20.0,NaN,NaN,11:30:00,...,420,0.935,1405.0,1105.0,2,4,3,2,2,3
28,sample_1002,300,0.0,405.0,700,14:00:00,21.0,NaN,NaN,15:00:00,...,380,0.878,1405.0,1105.0,2,4,3,2,2,3
29,sample_1079,300,0.0,405.0,700,1:00:00,27.0,NaN,NaN,2:30:00,...,400,0.902,1405.0,1105.0,2,4,3,2,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1516,sample_49,300,0.0,405.0,700,22:00:00,20.0,NaN,NaN,23:00:00,...,400,-1.000,1405.0,1105.0,2,4,3,2,2,3
1517,sample_474,300,0.0,405.0,700,12:00:00,32.0,NaN,NaN,13:30:00,...,400,-1.000,1405.0,1105.0,2,4,3,2,2,3
1518,sample_1716,300,0.0,405.0,700,5:00:00,18.0,NaN,NaN,6:30:00,...,400,-1.000,1405.0,1105.0,2,4,3,2,2,3
1519,sample_1169,300,0.0,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,420,-1.000,1405.0,1105.0,2,4,3,2,2,3
1520,sample_1925,300,0.0,405.0,700,6:00:00,30.0,NaN,NaN,8:00:00,...,440,-1.000,1405.0,1105.0,2,4,3,2,2,3
1521,sample_667,300,0.0,405.0,700,22:00:00,30.0,NaN,NaN,0:00:00,...,400,-1.000,1405.0,1105.0,2,4,3,2,2,3
1522,sample_176,300,0.0,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,400,-1.000,1405.0,1105.0,2,4,3,2,2,3
1523,sample_1908,300,0.0,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,400,-1.000,1405.0,1105.0,2,4,3,2,2,3
1524,sample_160,300,0.0,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,400,-1.000,1405.0,1105.0,2,4,3,2,2,3
1525,sample_35,300,0.0,405.0,700,22:00:00,21.0,NaN,NaN,23:00:00,...,440,-1.000,1405.0,1105.0,2,4,3,2,2,3
1526,sample_1403,300,0.0,405.0,700,21:00:00,29.0,NaN,NaN,23:00:00,...,440,-1.000,1405.0,1105.0,2,4,3,2,2,3
1527,sample_1806,300,0.0,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,420,-1.000,1405.0,1105.0,2,4,3,2,2,3
1528,sample_241,300,0.0,405.0,700,6:00:00,30.0,NaN,NaN,8:00:00,...,440,-1.000,1405.0,1105.0,2,4,3,2,2,3
1529,sample_1059,300,0.0,405.0,700,16:30:00,21.0,NaN,NaN,18:00:00,...,420,-1.000,1405.0,1105.0,2,4,3,2,2,3
1530,sample_746,300,0.0,405.0,700,22:00:00,29.0,NaN,NaN,0:00:00,...,440,-1.000,1405.0,1105.0,2,4,3,2,2,3
1531,sample_513,300,0.0,405.0,700,22:30:00,21.0,NaN,NaN,0:00:00,...,420,-1.000,1405.0,1105.0,2,4,3,2,2,3
1532,sample_1088,300,0.0,405.0,700,15:30:00,26.0,NaN,NaN,16:00:00,...,420,-1.000,1405.0,1105.0,2,4,3,2,2,3
1533,sample_1370,300,0.0,405.0,700,6:00:00,28.0,NaN,NaN,8:00:00,...,440,-1.000,1405.0,1105.0,2,4,3,2,2,3
1534,sample_523,300,0.0,405.0,700,5:00:00,23.0,NaN,NaN,6:30:00,...,420,-1.000,1405.0,1105.0,2,4,3,2,2,3
1535,sample_319,300,0.0,405.0,700,21:00:00,37.0,0:50:00,80.0,22:50:00,...,400,-1.000,1405.0,1105.0,2,4,3,2,2,3
1536,sample_1923,300,0.0,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,460,-1.000,1405.0,1105.0,2,4,3,2,2,3
1537,sample_1296,300,0.0,405.0,700,21:00:00,30.0,NaN,NaN,23:00:00,...,440,-1.000,1405.0,1105.0,2,4,3,2,2,3
1538,sample_1152,300,0.0,405.0,700,18:00:00,29.0,NaN,NaN,20:00:00,...,400,-1.000,1405.0,1105.0,2,4,3,2,2,3
1539,sample_982,300,0.0,405.0,700,22:00:00,21.0,NaN,NaN,23:30:00,...,400,-1.000,1405.0,1105.0,2,4,3,2,2,3
1540,sample_304,300,125.0,0.0,980,17:00:00,21.0,NaN,NaN,18:30:00,...,400,-1.000,1405.0,1105.0,3,3,4,3,3,0
1541,sample_502,300,0.0,405.0,700,11:00:00,24.0,NaN,NaN,12:30:00,...,440,-1.000,1405.0,1105.0,2,4,3,2,2,3
1542,sample_1951,300,0.0,405.0,700,21:00:00,29.0,NaN,NaN,23:00:00,...,440,-1.000,1405.0,1105.0,2,4,3,2,2,3
1543,sample_386,300,0.0,405.0,700,7:30:00,41.0,7:40:00,80.0,9:00:00,...,440,-1.000,1405.0,1105.0,2,4,3,2,2,3
1544,sample_362,300,0.0,405.0,700,2:00:00,36.0,2:10:00,80.0,3:30:00,...,420,-1.000,1405.0,1105.0,2,4,3,2,2,3
1545,sample_522,300,0.0,405.0,700,22:00:00,29.0,NaN,NaN,23:30:00,...,420,-1.000,1405.0,1105.0,2,4,3,2,2,3

In [59]:
all_df = data_cleaning_pipline(all_df)

In [ ]:
all_df.columns

In [60]:
data_box = DataBox(all_df)

In [62]:
lgb_model(data_box)

Training until validation scores don't improve for 200 rounds.
[200]	training's l2: 0.000338871	valid_1's l2: 0.000230935
[400]	training's l2: 0.000275602	valid_1's l2: 0.000206564
[600]	training's l2: 0.000253317	valid_1's l2: 0.000199659
[800]	training's l2: 0.000240146	valid_1's l2: 0.000198816
[1000]	training's l2: 0.00023097	valid_1's l2: 0.000197687
[1200]	training's l2: 0.000223816	valid_1's l2: 0.000197502
[1400]	training's l2: 0.00021791	valid_1's l2: 0.000196984
[1600]	training's l2: 0.000212931	valid_1's l2: 0.00019665
[1800]	training's l2: 0.000208616	valid_1's l2: 0.000195925
[2000]	training's l2: 0.000204566	valid_1's l2: 0.000195799
Early stopping, best iteration is:
[1876]	training's l2: 0.000207042	valid_1's l2: 0.000195556